### ISSUE TITLE
哥，你的自述文件是不是删了呀？

### ISSUE THREAD

**Issue by DORAEM000N** [LihaoLikeOrangeJuice/clock-in-gzhu#12]
还是我的问题？没看到自述文件了...

**Comment by LihaoLikeOrangeJuice** [comment]
删了，感觉这个脚本传播得太广了不太好

**Comment by DORAEM000N** [comment]
> 

好吧，最近打卡不成功，准备重新fork一下，结果....TAT

**Comment by LihaoLikeOrangeJuice** [comment]
和原来的设置方法没有区别吧，而且你看commits的记录是能看到的 https://github.com/LihaoLikeOrangeJuice/clock-in-gzhu/commit/ceba97f9ee0e034bfded8c479d50149c36c7a42d
